package export

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/rey4L/gbase"
)

var bg = context.Background()

func sample(t *testing.T) *gbase.DB {
	t.Helper()
	db, e := gbase.Open(filepath.Join(t.TempDir(), "app.db"))
	if e != nil {
		t.Fatal(e)
	}
	t.Cleanup(func() { db.Close() })
	for _, q := range []string{
		`CREATE TABLE clients (id INTEGER PRIMARY KEY, name TEXT NOT NULL, "user" TEXT, size INTEGER, active BOOLEAN NOT NULL DEFAULT 1, since DATE, seen TIMESTAMP DEFAULT '2026-01-01', photo BLOB, score REAL, parent INTEGER REFERENCES clients(id), UNIQUE (name, "user"))`,
		`CREATE TABLE policies (id INTEGER PRIMARY KEY, client INTEGER NOT NULL REFERENCES clients(id), num TEXT UNIQUE, notes TEXT)`,
		`CREATE INDEX policies_client ON policies (client, num)`,
		`INSERT INTO clients (name, "user", size, since, seen, photo, score) VALUES ('Ada "the" Count', 'ada', 3, '2026-01-15', '2026-03-01T10:00:00.5-04:00', X'00FF10', 2.5)`,
		`INSERT INTO clients (name, "user", parent, active) VALUES ('line1
line2, with comma', NULL, 1, 0)`,
		`INSERT INTO clients (name, "user") VALUES ('line1
line2, with comma', '')`,
		`INSERT INTO clients (name) VALUES ('')`,
		`INSERT INTO clients (name) VALUES ('temp')`,
		`DELETE FROM clients WHERE name = 'temp'`,
		`INSERT INTO policies (client, num, notes) VALUES (1, 'P-1', ?)`,
	} {
		args := []any{}
		if strings.Contains(q, "?") {
			args = append(args, strings.Repeat("x", 5000))
		}
		if _, e := db.Exec(bg, q, args...); e != nil {
			t.Fatalf("%s: %v", q, e)
		}
	}
	return db
}

func read(t *testing.T, dir, name string) string {
	t.Helper()
	b, e := os.ReadFile(filepath.Join(dir, name))
	if e != nil {
		t.Fatal(e)
	}
	return string(b)
}

func contains(t *testing.T, label, s string, want ...string) {
	t.Helper()
	for _, w := range want {
		if !strings.Contains(s, w) {
			t.Errorf("%s missing %q:\n%s", label, w, s)
		}
	}
}

func TestPostgres(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "out")
	r, e := Export(bg, sample(t), dir, Postgres)
	if e != nil {
		t.Fatal(e)
	}
	contains(t, "schema.sql", read(t, dir, "schema.sql"),
		"CREATE TABLE clients (\n  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 6) PRIMARY KEY,\n  name TEXT NOT NULL,\n  \"user\" TEXT,\n  size BIGINT,\n  active BOOLEAN DEFAULT TRUE NOT NULL,\n  since DATE,\n  seen TIMESTAMPTZ DEFAULT '2026-01-01T00:00:00.000000Z',\n  photo BYTEA,\n  score DOUBLE PRECISION,\n  parent BIGINT,\n  UNIQUE (name, \"user\")\n);",
		"num TEXT UNIQUE",
	)
	contains(t, "constraints.sql", read(t, dir, "constraints.sql"),
		"CREATE INDEX policies_client ON policies (client, num);",
		"ALTER TABLE clients ADD FOREIGN KEY (parent) REFERENCES clients (id) ON DELETE RESTRICT ON UPDATE RESTRICT;",
		"ALTER TABLE policies ADD FOREIGN KEY (client) REFERENCES clients (id)",
	)
	csv := read(t, dir, "01_clients.csv")
	want := `"id","name","user","size","active","since","seen","photo","score","parent"
1,"Ada ""the"" Count","ada",3,t,"2026-01-15","2026-03-01T14:00:00.500000Z",\x00ff10,2.5,
2,"line1
line2, with comma",,,f,,"2026-01-01T00:00:00.000000Z",,,1
3,"line1
line2, with comma","",,t,,"2026-01-01T00:00:00.000000Z",,,
4,"",,,t,,"2026-01-01T00:00:00.000000Z",,,
`
	if csv != want {
		t.Errorf("clients CSV:\n%s\nwant:\n%s", csv, want)
	}
	contains(t, "load.sql", read(t, dir, "load.sql"),
		"\\i schema.sql\n\\copy clients FROM '01_clients.csv' WITH (FORMAT csv, HEADER true)\n\\copy policies FROM '02_policies.csv' WITH (FORMAT csv, HEADER true)\n\\i constraints.sql\nCOMMIT;")
	if len(r.Tables) != 2 || r.Tables[0].Rows != 4 || r.Tables[1].Rows != 1 {
		t.Errorf("tables %+v", r.Tables)
	}
	report := strings.Join(r.Warnings, "\n")
	contains(t, "warnings", report, `user is reserved in PostgreSQL`)
	if strings.Contains(report, "size") || strings.Contains(report, "empty strings") {
		t.Errorf("PostgreSQL got Oracle warnings:\n%s", report)
	}
	contains(t, "REPORT.md", read(t, dir, "REPORT.md"), "| clients | 01_clients.csv | 4 |", "psql -d DATABASE -f load.sql")

	if _, e = Export(bg, sample(t), dir, Postgres); e == nil {
		t.Fatal("exported into a non-empty directory")
	}
	if _, e = Export(bg, sample(t), t.TempDir(), "mysql"); e == nil {
		t.Fatal("unknown dialect accepted")
	}
}

func TestOracle(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "out")
	r, e := Export(bg, sample(t), dir, Oracle)
	if e != nil {
		t.Fatal(e)
	}
	schema := read(t, dir, "schema.sql")
	contains(t, "schema.sql", schema,
		"WHENEVER SQLERROR EXIT FAILURE",
		"ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (START WITH 6) PRIMARY KEY",
		"NAME VARCHAR2(4000 BYTE) NOT NULL",
		`"USER" VARCHAR2(4000 BYTE)`,
		`"SIZE" NUMBER(19)`,
		"ACTIVE NUMBER(1) DEFAULT 1 NOT NULL CHECK (ACTIVE IN (0, 1))",
		"SEEN TIMESTAMP(6) DEFAULT TIMESTAMP '2026-01-01 00:00:00.000000'",
		"PHOTO BLOB",
		"SCORE BINARY_DOUBLE",
		`UNIQUE (NAME, "USER")`,
		"NOTES CLOB",
		"EXIT\n",
	)
	csv := read(t, dir, "01_clients.csv")
	if !strings.HasPrefix(csv, "\"id\",\"name\",\"user\",\"size\",\"active\",\"since\",\"seen\",\"photo\",\"score\",\"parent\"\x1e\n1,\"Ada \"\"the\"\" Count\",\"ada\",3,1,\"2026-01-15\",\"2026-03-01 14:00:00.500000\",\"blobs/01_clients/1_8.bin\",2.5,\x1e\n2,\"line1\nline2, with comma\",,,0,") {
		t.Errorf("clients CSV:\n%q", csv)
	}
	if b, e := os.ReadFile(filepath.Join(dir, "blobs", "01_clients", "1_8.bin")); e != nil || string(b) != "\x00\xff\x10" {
		t.Errorf("blob file: %q %v", b, e)
	}
	contains(t, "ctl", read(t, dir, "01_clients.ctl"),
		"INFILE '01_clients.csv' \"str X'1E0A'\"",
		"APPEND INTO TABLE CLIENTS",
		"NAME CHAR(23)",
		`SEEN TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF6"`,
		`SINCE DATE "YYYY-MM-DD"`,
		"LOB_FILE_8 FILLER CHAR(4000),\n  PHOTO LOBFILE(LOB_FILE_8) TERMINATED BY EOF NULLIF LOB_FILE_8 = BLANKS",
	)
	contains(t, "ctl", read(t, dir, "02_policies.ctl"), "NOTES CHAR(5000)")
	contains(t, "load.sh", read(t, dir, "load.sh"), "sqlplus -s -L \"$conn\" @schema.sql", "control=01_clients.ctl", "@constraints.sql")
	if info, _ := os.Stat(filepath.Join(dir, "load.sh")); info.Mode()&0o100 == 0 {
		t.Error("load.sh not executable")
	}
	report := strings.Join(r.Warnings, "\n")
	contains(t, "warnings", report,
		"size is reserved in Oracle",
		"user is reserved in Oracle",
		"clients.name: 1 empty strings will fail to load",
		"clients.user: 1 empty strings will load as NULL",
		"clients UNIQUE (name, user): 1 rows repeat",
	)
}
